# -*- coding: utf-8 -*-
"""Iris_flower_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbztKnvlEsTqy3P3E4M8k4Io4jP1mhmu
"""

# train models.py
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import joblib

#load data
iris = load_iris()
x, y =iris.data, iris.target

#train model
model = LogisticRegression(max_iter=200)
model.fit(x,y)

#save model
joblib.dump(model, 'iris_model.pkl')